version: '3.8'

services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql-library
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - library-network
  backend:
    build: ./backend
    container_name: backend-library
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - library-network
  frontend:
    build: ./frontend/library
    container_name: frontend-library
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - library-network
networks:
  library-network:
volumes:
  mysql_data:
