spring:
  application:
    name: libraryApi
  datasource:
    url: jdbc:mysql://localhost:3307/library
    user: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update